### ISSUE TITLE
DrawItem event for KryptonComboBox

### ISSUE THREAD

**Issue by mace17** [Wagnerp/Krypton-NET-5.470#198]
Hi, I can't find DrawEvent for KryptonComboBox , should it be here https://github.com/Wagnerp/Krypton-NET-5.471 or it's available only for extended toolkit ?

**Comment by Smurf-IV** [comment]
For some reason the event is hidden in the designer, but it is a public Event that can be attched to:

        /// <summary>
        /// Occurs when [draw item].
        /// </summary>
        [Browsable(false)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public event DrawItemEventHandler DrawItem;

**Comment by Wagnerp** [comment]
All events are set to `[Browsable(false)]`?????

**Comment by Smurf-IV** [comment]
From what I can understand in the `WinForm` code....
If an event exists in a base class, and it directly derived, and an event is being replaced then, `[Browsable(false)]` is used, e.g.

        [Browsable(false)]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public new event EventHandler TextChanged;

If it is a new event, then it need to be exposed, so that the designer can pick it up, e.g.

        [Description("Raises the TrackMouseLeave event in the wrapped control.")]
        [Category("Mouse")]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public event EventHandler TrackMouseLeave;

So, As the `public event DrawItemEventHandler DrawItem;` is an event just for the KCB, then it should have the exposure into the designer for it to be usable.
