### ISSUE TITLE
[New Feature Request]: Blur form when inactive

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-NET-5.470#240]
Blur form when inactive

i.e

![image](https://user-images.githubusercontent.com/949607/69269823-ba4a8780-0bc9-11ea-9048-5b3e03c23ee4.png)

**Comment by Wagnerp** [comment]
https://frasergreenroyd.com/c-gui-blurring-focus-on-a-parent-window-when-using-pop-up-windows/

**Comment by Smurf-IV** [comment]
> https://frasergreenroyd.com/c-gui-blurring-focus-on-a-parent-window-when-using-pop-up-windows/

That is for `PresentationCore` applications !

**Comment by Smurf-IV** [comment]
Also, the Blurring should include the title bar and the forms borders, to be really accurate.

**Comment by Smurf-IV** [comment]
Using the code from here (And using `ACCENT_ENABLE_BLURBEHIND` to work on Window 8 and 10)
Does not change the Krypton drawn values, only the windows default form elements:
![image](https://user-images.githubusercontent.com/2418812/70799268-08a20f00-1da1-11ea-8cb7-e0dbc718b09c.png)

**Comment by Smurf-IV** [comment]
Using an adaption of the panel (Or use the form itself) from the following code 
https://stackoverflow.com/questions/17248748/c-sharp-dialog-form-with-blur-background
gives this:
![image](https://user-images.githubusercontent.com/2418812/70800215-93840900-1da3-11ea-9246-38dc0d4d87f3.png)
Notice how the areas that were blurred via the `ACCENT_ENABLE_BLURBEHIND` are not in this version. Also the Gaussian blur needs to go further (The value 1 (highest) was used for this)

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

Thanks for looking into this, just thought that it would be a nice addition to the toolkit.

**Comment by Smurf-IV** [comment]
How about this ?
![image](https://user-images.githubusercontent.com/2418812/70813032-b53fb900-1dc0-11ea-90c1-f95d14283ecf.png)
I'll also have options to allow active areas to "Sort of" show through (i.e. if there is progress bar, or timer ticking by, by adjust the amount of "Fizz" and Opaqueness of the image overlay.
There is still 1 problem (or 2) you can see in the image above, that the [Help] tooltip is still visible, even tho the MessageBox is topmost.

**Comment by Wagnerp** [comment]
That looks good, the idea really is to make the user focus on the messagebox/top level window. Maybe also allow the user to adjust the amount of blur? On another note should I take out the `KryptonInputBox` since I've developed a better version in the extended toolkit?

**Comment by Smurf-IV** [comment]
re: `KryptonInputBox`: If you have a better one, then move it into the Toolkit as an identically named component, otherwise you will break upgrading of the toolkit via NuGet and project developers will get upset !

**Comment by Wagnerp** [comment]
Will do, though I may save some of the more 'advanced' features, i,e setting a image, user selection, mask etc back for the extended toolkit.

**Comment by Smurf-IV** [comment]
The following zip file shows a movie of the form "Blurring" when a message box is opened:
[BlurWhenMessageBoxOpens.zip](https://github.com/Wagnerp/Krypton-NET-5.470/files/3963843/BlurWhenMessageBoxOpens.zip)
Then when another window "Pops" over the parent form, it is unblurred (Otherwise the topmost blurring will have shown on top)
4 values are now available on a forms designer:
![image](https://user-images.githubusercontent.com/2418812/70848905-0ce92d80-1e70-11ea-8d47-6911c67e6911.png)

The Opacity is useful if the Parent Form has active updates going on (Like a progress or a timestamp as demonstrated in the movie), but can be set to a high value to force the blurring to full effect.
Not Sure how useful the "Blur When Focus Lost is" as it forces a blurred window into any window that crosses over the parent form. But Hey it's there if someone wants to use it :-)

**Comment by Wagnerp** [comment]
Hi @Smurf-IV 

Just wondering, does this line need commenting out `_blurredForm.Save(@"Z:\_blurredForm.png");` as it crashes the app or do I need to put a dynamic variable in?

**Comment by Wagnerp** [comment]
The other problem with `_blurredForm.Save(@"Z:\_blurredForm.png");` is that it may act like a zombie i.e eating up space unless images are deleted.

**Comment by Smurf-IV** [comment]
Good catch, 
Left in due to debugging, and then having a Migraine!
No it would not have "Eaten" space as it is quite small (Form size) and is replaced each time,
But it could have thrown an exeption which would have prevented the blur, and also it could slow down the blurring action if the target was a slow drive.
